### PR TITLE
Unitary learning tutorial with qgrad

### PR DESCRIPTION
**Pull request by araza6**
Opening this with notebook here since I can't import qgrad_qutip in the examples repo for now. Turns out JAX's grad is not merely a one-liner to be used with cost functions just like that. 

I write the JAX-comptabile cost function 

```
def cost(params, inputs, outputs):
    r"""Calculates the cost/error on the whole training datat set.
    
    Args:
    ----
        params: parameters :math:`\t` and :math:`\tau` in :math:`U^{\dagger} U(\vec{t},\vec{\tau})`
        inputs: input kets :math:`|\psi_{l}>` in the dataset
        outputs: output kets :math:`U(\vec{t}, \vec{\tau})*|ket\_input>` in the dataset
    
    Returns:
    -------
        cost (float): cost (evaluated on the entire dataset) of parametrizing 
                     :math:`\tau` in :math:`U^{\dagger} U(\vec{t},\vec{\tau})` with `params`                  
    """
    loss = 0.0
    for k in range(train_len):
        pred = jnp.dot(make_unitary(N, params), inputs[k]) #prediction wth parametrized unitary
        loss += jnp.absolute(jnp.real(jnp.dot(outputs[k].conjugate().T, pred)))
        # TODO check real and abs in loss above since   
        # it's not in the original paper
    loss = 1 - (1 / train_len) * loss
    return loss[0][0]
```

but it does not work with `grad` and throws the following error: 

> ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop. Try using lax.scan instead

One way hack this, as is also suggested in this [issue](https://github.com/google/jax/issues/2956) is to forcefully trigger the `scan` function by setting the condition in line 203 (in jax/lax/lax_control_flow.py). This does not help either. 

Turns out that if the cost function, or the function one wishes to differentiate in general, contains loops, JAX unrolls the loops in a 'functional' way and asks to follow [this](https://jax.readthedocs.io/en/latest/jax.experimental.loops.html). And so I write cost function as: 

```
def cost_jax(params, inputs, outputs):
    with loops.Scope() as s:
        s.loss = 0.0
        s.params = params
        s.inputs = inputs
        s.outputs = outputs
        s.N = N
        s.train_len = train_len
        for k in range(train_len):
            s.pred = jnp.dot(make_unitary(s.N, s.params), s.inputs[k])
            s.loss += jnp.absolute(jnp.real(jnp.dot(s.outputs[k].conjugate().T, s.pred)))
        s.loss = 1 - (1 / s.train_len) * s.loss
        return s.loss[0][0]
```

This evaluates the _value_ of the cost function without any bugs, but `grad` still gives the same error. 

For all the other tutorials that we used `grad` for, they (luckily!) did not require involve loops since it was just some parametrized operator acting on one state and fidelity with the evolved state was returned. Here, we evaluate loss on whole data set that requires summing over the loss for each point (or a few points in case of SGD), which requires loops. One way might be to call a helper function within cost, say `predict` to run a for loop in that `predict`. Another way would be to vectorize operations maybe?

Thoughts?

### CODE REVIEW

**Comment by quantshah** [comment]
I suppose we discussed this last time. Any updates on whether this works with a `predict` function where you will have the loop through the unitaries and get the predicted output vector? This is similar to running a many-hidden-layer neural network and should not be an issue. Also, in any neural network training, you will calculate the cost function as a sum of the individual losses (eg., mean squared loss) for many training examples. Check how that would work with jax since you will essentially be looping over all the training examples. Good luck.

**Comment by araza6** [comment]
I had tried writing a separate function earlier on. A loss function like this
```
def loss(params, inputs, outputs):
    loss_val = 0.0
    unit = make_unitary(N, params)
    for k in range(train_len):
        pred = jnp.dot(unit, inputs[k]) #prediction wth parametrized unitary
        loss_val += jnp.absolute(jnp.real(jnp.dot(outputs[k].conjugate().T, pred)))
    return loss_val
```
And then the cost 
```
def cost(params, inputs, outputs):
    r"""Calculates the cost on the whole training dataset.
    
    Args:
    ----
        params: parameters :math:`\t` and :math:`\tau` in :math:`U^{\dagger} U(\vec{t},\vec{\tau})`
        inputs: input kets :math:`|\psi_{l}>` in the dataset
        outputs: output kets :math:`U(\vec{t}, \vec{\tau})*|ket\_input>` in the dataset
    
    Returns:
    -------
        cost (float): cost (evaluated on the entire dataset) of parametrizing 
                     :math:`\tau` in :math:`U^{\dagger} U(\vec{t},\vec{\tau})` with `params`                  
    """
    '''
    loss = 0.0
    for k in range(train_len):
        pred = jnp.dot(make_unitary(N, params), inputs[k]) 
        loss += jnp.absolute(jnp.real(jnp.dot(outputs[k].conjugate().T, pred)))
        # TODO check real and abs in loss above since   
        # it's not in the original paper
    '''

    loss_val = 1 - (1 / train_len) * loss(params, inputs, outputs)
    return loss_val[0][0]
```
It still returned the same Error

> ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop. Try using lax.scan instead

A user kindly suggested (on JAx's repo [here](https://github.com/google/jax/issues/2956#issuecomment-662568765)) what may the source of error here. And that is something we have discussed earlier as well. It is the fact that the `make_unitary` function

```
def make_unitary(N, params):
    r"""Retruns a paramterized unitary matrix.
    
    : math:: \begin{equation}\label{decomp}
                U(\vec{t}, \vec{\tau}) = e^{-iB\tau_{N}}e^{-iAt_{N}} ... e^{-iB\tau_{1}}e^{-iAt_{1}}
             \end{equation}
             
    Args:
    ----
        N (int): Size of the parameter vectors, :math:`\tau` and :math:`\t`
        params (:obj:`np.ndarray`): parameter vector of size :math:`2 * N` where the first half parameters are  
                                   :math:`\vec{t}` params and the second half encodes \vec{\tau}) parameters.
                                   
    Returns:
        unitary (:obj:`np.ndarray`): numpy array representation of paramterized unitary matrix 
    """
    unitary = jnp.eye(d)
    params = jnp.array(params)
    for i in range (N): 
        unitary = jnp.matmul(jnp.matmul(expm(-1j * B * params[i + N][0]),
                                        expm(-1j * A * params[i][0])), unitary)
    
    return unitary 
```

exponentiates a complex matrix, B by expm(B) and JAX's  `grad(expm(B))` expm still a WIP as Matt says [here](https://github.com/google/jax/issues/2519#issuecomment-604605377).

**Comment by araza6** [comment]
Actually, the forward mode diff of `expm` is merged on https://github.com/google/jax/pull/2062, but the reverse mode is still a WIP https://github.com/google/jax/issues/3447

**Comment by quantshah** [comment]
Ah I see. The construction of the N x N unitary is done using `expm(-iH)` where H is Hermitian. In case of the 2x2 unitary you notice that is has a parameterisation in terms of sines and cosines where you do not require the matrix exponential. We must be able to find alternative ways to construct N x N unitaries which do not involve ´expm´ similar to what we found for the `Displace` operator. Consider this from the supplementary part of the paper [Deep learning with coherent nanophotonic circuits](https://www.nature.com/articles/nphoton.2017.93) by Shen et. al, 2017:
Screenshot 2020-07-23 08 52 22


If you take this decomposition, you will be able to parameterise your N x N unitary with just sines and cosines of the 2**N theta parameters. This should then allow us to circumvent the `expm` issue. If you are familiar with recursive methods then there is also this construction: [A recursive parametrization of unitary matrices](https://aip.scitation.org/doi/full/10.1063/1.2038607) (C Jarlskog 2005) which decomposes the N x N unitary using a diagonal matrix similar to the Displace function.

**Comment by nathanshammah** [comment]
@araza6 is this PR review ready?

**Comment by araza6** [comment]
Not yet, there is the non-autodifferentiable unitary matrix issue in works

**Comment by araza6** [comment]
The fidelity values are exploding. This is possibly due to the fact that the parametrized unitary generator does not really give a unitary that preserves ket norm, thereby exploding fidelity values -- apparently monotonically. I make a 2 x 2 unitary using the scheme shown in [this paper](https://aip.scitation.org/doi/full/10.1063/1.2038607) in equation 19. 

When I test the function, it appears that the matrix generated is indeed not a unitary. To reproduce,

```python
import jax.numpy as jnp
from jax import ops

from qgrad.qgrad_qutip import dag

def rot(theta):
    return jnp.array([
        [jnp.cos(theta), jnp.sin(theta)],
        [-jnp.sin(theta), jnp.cos(theta)],
    ])

def make_unitary_by_rot(alphas, betas, theta):
    alpha_mat = beta_mat = jnp.zeros((2, 2))
    # Fill diagonals of the alpha matrix
    alpha_mat = ops.index_update(alpha_mat, ops.index[0, 0], alphas[0])
    alpha_mat = ops.index_update(alpha_mat, ops.index[1, 1], alphas[1])
    # Fill diagonals of the beta matrix
    beta_mat = ops.index_update(beta_mat, ops.index[0, 0], betas[0])
    beta_mat = ops.index_update(beta_mat, ops.index[1, 1], betas[1])
    
    tmp = jnp.dot(alpha_mat, rot(theta))
    return jnp.dot(tmp, beta_mat)

# Test here
alphas = jnp.array([0.1, 0.2])
betas = jnp.array([0.3, 0.4])
theta = jnp.array(0.5)
U = make_unitary_by_rot(alphas, betas, theta)
alphas = jnp.array([0.1, 0.2])
betas = jnp.array([0.3, 0.4])
theta = jnp.array(0.5)
U = make_unitary_by_rot(alphas, betas, theta)
print("U_UD",jnp.dot(U, dag(U)))
print("UD_U",jnp.dot(dag(U), U))
```
This returns 

```
U_UD [[0.00106089 0.00058903]
 [0.00058903 0.00575642]]
UD_U [[ 0.00152059 -0.00151465]
 [-0.00151465  0.00529673]]
```

**Comment by araza6** [comment]
This is ready for review. Two points:

1. Learning sometimes changes dramatically with different random datasets
2. Although the evolved kets have a very high density, the crude unitary matrices are not very much the same
cc: @quantshah

**Comment by araza6** [comment]
The random seed is not available for scipy's unitary group, through which we make our target unitary

```python
from scipy.stats import unitary_group
tar_unitr = jnp.asarray(unitary_group.rvs(N))
```

So the results in the notebook will not be 100 % reproducible in that the user might have to try different runs to get a good convergence

**Review by quantshah — APPROVED** [review]

**Pull request merged**
