### PR TITLE
Added .gitignore to remove .ipynb_checkpoints

### PR DESCRIPTION
**Pull request by araza6**
For now, I have added .gitignore to simply ignore .ipynb_checkpoints. It can be made more sophisticated to ignore more file types. But for now, I don't foresee any. We shall prolong this as we go on.

### CODE REVIEW

**Comment by araza6** [comment]
Somehow, it is showing my previous commits too even on a new branch. I am doing something wrong with branches

**Comment by nathanshammah** [comment]
You are inheriting the commits and related file changes from the branch `araza6:qubit_rotation` of PR #2 because your origin master branch (`araza6/qgrad`) is not synced with the upstream (`qgrad/qgrad`). Indeed it says: "This branch is 5 commits ahead, 4 commits behind qgrad:master."
If you were not in this situation, A way to avoid this is this:

- Switch to the local master branch, pull from upstream, open a new branch, [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commit of this PR or do them again. 

- Alternatively, you can do a `git rebase` of your local gitignore branch with respect to the upstream master, resolve eventual conflicts, and then apply again the changes. 

In general you want to have the master in sync with upstream.

**Comment by quantshah** [comment]
Any updates on this? @araza6 Please look at Nathan's comments and update this PR. I could help you learn how to rebase if you need to. 

A simple way would be to first update your own master branch

git checkout master                               # go to your local master branch i.e., araza6/qgrad/master
git pull upstream master                       # update locally your master branch to the upstream 
git push origin master                           # update your online remote master branch

Then you could go back to your gitignore branch and rebase against the master:
git pull --rebase origin master

This brings you up-to-date with you origin master (which you synced in the previous step). Then make your changes and commit. And then push again.

Two good practices are 
- always update your origin master to the upstream before you branch out
- before pushing your commits for the final merge, you should update your origin master and rebase your PR against the upstream master

**Comment by quantshah** [comment]
Here is a tutorial on how to do that:
https://itnext.io/level-up-git-rebasing-and-squashing-6bff432d796e

**Comment by quantshah** [comment]
Since you did not rebase this @araza6 , I went ahead and took care of the gitginore, also adding a lot of other python files. So this can be closed now. But do have a look at the links to understand rebase better as we might need them later.

**Pull request closed without merging**
