### PR TITLE
Continuous Integration

### PR DESCRIPTION
**Pull request by araza6**
Continuous Integration setup

### CODE REVIEW

**Comment by nathanshammah** [comment]
Not sure of this error message
```
ERROR: Could not find a version that satisfies the requirement gfortran (from versions: none)
ERROR: No matching distribution found for gfortran
##[error]Process completed with exit code 1.
```
Do you need gfortran for jax?

**Comment by araza6** [comment]
> Not sure of this error message
> 
> ```
> ERROR: Could not find a version that satisfies the requirement gfortran (from versions: none)
> ERROR: No matching distribution found for gfortran
> ##[error]Process completed with exit code 1.
> ```
> 
> Do you need gfortran for jax?

Now that error messages is surpassed for 3.7 build. 3.8 is still running

**Comment by araza6** [comment]
> Not sure of this error message
> 
> ```
> ERROR: Could not find a version that satisfies the requirement gfortran (from versions: none)
> ERROR: No matching distribution found for gfortran
> ##[error]Process completed with exit code 1.
> ```
> 
> Do you need gfortran for jax?

A quick search seems to suggest that had to do with scipy, and not JAX

**Comment by nathanshammah** [comment]
The gfortran issue is strange, I never had to install it for scipy. Glad that now tests pass. Merging!

**Pull request merged**
